export const productActionType = {
    ALL_PRODUCT_REQUEST : "ALL_PRODUCT_REQUEST",
    ALL_PRODUCT_SUCCESS : "ALL_PRODUCT_SUCCESS",
    ALL_PRODUCT_FAIL : "ALL_PRODUCT_FAIL",

    PRODUCT_DETAILS_REQUEST : "PRODUCT_DETAILS_REQUEST",
    PRODUCT_DETAILS_SUCCESS : "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_FAIL : "PRODUCT_DETAILS_FAIL",

    CLEAR_ERRORS : "CLEAR_ERRORS"
}