export const userActionType = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAIL : "LOGIN_FAIL",

    REGISTER_USER_REQUEST : "REGISTER_USER_REQUEST",
    REGISTER_USER_SUCCESS : "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAIL : "REGISTER_USER_FAIL",

    LOAD_USER_REQUEST : "LOAD_USER_REQUEST",
    LOAD_USER_SUCCESS : "LOAD_USER_SUCCESS",
    LOAD_USER_FAIL : "LOAD_USER_FAIL",

    LOGOUT_REQUEST : "LOGOUT_REQUEST",
    LOGOUT_SUCCESS : "LOGOUT_SUCCESS",
    LOGOUT_FAIL : "LOGOUT_FAIL",

    UPDATE_PROFILE_REQUEST : "UPDATE_PROFILE_REQUEST",
    UPDATE_PROFILE_SUCCESS : "UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_RESET : "UPDATE_PROFILE_RESET",
    UPDATE_PROFILE_FAIL : "UPDATE_PROFILE_FAIL",

    CLEAR_ERRORS : "CLEAR_ERRORS"
}